### PR TITLE
Updating to Ng 14

### PR DESCRIPTION
**Pull request by chrux**
Merge or review https://github.com/arielfaur/ionic-pullup/pull/79 first

### CODE REVIEW

**Comment by chrux** [comment]
I forgot to migrate to eslint, will do the change first

**Comment by arielfaur** [comment]
Hey @chrux ! It would be great if you could do the upgrade as I don't have time now. I see you closed your PRs. Any issues with that?
I can look at your PR over the weekend. Thanks!

**Comment by chrux** [comment]
Hello, thanks for replying so quickly and sorry I couldn't answer before, this the PR with the changes, pls let me know what you think, https://github.com/arielfaur/ionic-pullup/pull/81, also I had to revert Ng 14 as this plugins for cordova was causing some issues `@ionic/cordova-builders`, but they just released version 7 which fixes the issue, https://github.com/ionic-team/angular-toolkit/issues/474#issuecomment-1188275342. I will create another PR once I had time to double check is working on my project.

**Comment by arielfaur** [comment]
Hey @chrux 
I merged your PR, great work thanks! Also, I updated the demo project 🎉

**Pull request closed without merging**
